// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBasemodels(t *testing.T) {
	t.Parallel()

	query := Basemodels()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBasemodelsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasemodelsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Basemodels().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasemodelsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BasemodelSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasemodelsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BasemodelExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Basemodel exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BasemodelExists to return true, but got false.")
	}
}

func testBasemodelsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	basemodelFound, err := FindBasemodel(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if basemodelFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBasemodelsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Basemodels().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBasemodelsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Basemodels().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBasemodelsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	basemodelOne := &Basemodel{}
	basemodelTwo := &Basemodel{}
	if err = randomize.Struct(seed, basemodelOne, basemodelDBTypes, false, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}
	if err = randomize.Struct(seed, basemodelTwo, basemodelDBTypes, false, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = basemodelOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = basemodelTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Basemodels().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBasemodelsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	basemodelOne := &Basemodel{}
	basemodelTwo := &Basemodel{}
	if err = randomize.Struct(seed, basemodelOne, basemodelDBTypes, false, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}
	if err = randomize.Struct(seed, basemodelTwo, basemodelDBTypes, false, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = basemodelOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = basemodelTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func basemodelBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func basemodelAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Basemodel) error {
	*o = Basemodel{}
	return nil
}

func testBasemodelsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Basemodel{}
	o := &Basemodel{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, basemodelDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Basemodel object: %s", err)
	}

	AddBasemodelHook(boil.BeforeInsertHook, basemodelBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	basemodelBeforeInsertHooks = []BasemodelHook{}

	AddBasemodelHook(boil.AfterInsertHook, basemodelAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	basemodelAfterInsertHooks = []BasemodelHook{}

	AddBasemodelHook(boil.AfterSelectHook, basemodelAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	basemodelAfterSelectHooks = []BasemodelHook{}

	AddBasemodelHook(boil.BeforeUpdateHook, basemodelBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	basemodelBeforeUpdateHooks = []BasemodelHook{}

	AddBasemodelHook(boil.AfterUpdateHook, basemodelAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	basemodelAfterUpdateHooks = []BasemodelHook{}

	AddBasemodelHook(boil.BeforeDeleteHook, basemodelBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	basemodelBeforeDeleteHooks = []BasemodelHook{}

	AddBasemodelHook(boil.AfterDeleteHook, basemodelAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	basemodelAfterDeleteHooks = []BasemodelHook{}

	AddBasemodelHook(boil.BeforeUpsertHook, basemodelBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	basemodelBeforeUpsertHooks = []BasemodelHook{}

	AddBasemodelHook(boil.AfterUpsertHook, basemodelAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	basemodelAfterUpsertHooks = []BasemodelHook{}
}

func testBasemodelsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBasemodelsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(basemodelColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBasemodelsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBasemodelsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BasemodelSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBasemodelsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Basemodels().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	basemodelDBTypes = map[string]string{`ID`: `integer`}
	_                = bytes.MinRead
)

func testBasemodelsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(basemodelPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(basemodelAllColumns) == len(basemodelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBasemodelsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(basemodelAllColumns) == len(basemodelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Basemodel{}
	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, basemodelDBTypes, true, basemodelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(basemodelAllColumns, basemodelPrimaryKeyColumns) {
		fields = basemodelAllColumns
	} else {
		fields = strmangle.SetComplement(
			basemodelAllColumns,
			basemodelPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BasemodelSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBasemodelsUpsert(t *testing.T) {
	t.Parallel()

	if len(basemodelAllColumns) == len(basemodelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Basemodel{}
	if err = randomize.Struct(seed, &o, basemodelDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Basemodel: %s", err)
	}

	count, err := Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, basemodelDBTypes, false, basemodelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Basemodel struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Basemodel: %s", err)
	}

	count, err = Basemodels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
