// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Basemodel   string
	Genbank     string
	Seqhash     string
	Seqhashlink string
	Uniprot     string
}{
	Basemodel:   "basemodel",
	Genbank:     "genbank",
	Seqhash:     "seqhash",
	Seqhashlink: "seqhashlink",
	Uniprot:     "uniprot",
}
